name: Scaffold Terraform Setup From Template

on:
  workflow_dispatch:
    inputs:
      workspace-name:
        description: 'Name for the workspace to setup. This should be unique'
        required: true 
        type: string

env:
  PR_BRANCH: "workflow/${{ inputs.workspace-name }}"
  ARM_TENANT_ID: '653fcdc1-a3dc-4588-96c4-ef684fc1232b'  
  STORAGE_ACCOUNT: sttfdevopsprimer01

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: '{
            "clientId": "${{ secrets.ARM_CLIENT_ID }}",
            "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
            "tenantId": "${{ env.ARM_TENANT_ID }}"
            }'

    - run: |
        az storage container create --name ${{ inputs.workspace-name }} --account-name ${{ env.STORAGE_ACCOUNT }} \--auth-mode login

    - run: |
        mkdir -p ./terraform-artifacts/${{ inputs.workspace-name }}

    - run: |
        sed s/\|workspace-name\|/${{ inputs.workspace-name }}/g ./.templates/main.tf.template > ./terraform-artifacts/${{ inputs.workspace-name }}/main.tf

    - run: |
        sed s/\|workspace-name\|/${{ inputs.workspace-name }}/g ./.templates/terraform-deploy.yml.template >> ./.github/workflows/terraform-deploy-${{ inputs.workspace-name }}.yml

    - uses: tibdex/github-app-token@v1
      id: generate_token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}     

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: ${{ env.PR_BRANCH }}
        token: ${{ steps.generate_token.outputs.token }}